'use client'
import {useMemo,useState} from 'react'
import Link from 'next/link'
type Item={asin:string;title:string;price:string;url:string}
const SELLER='A3RY4E0FMNTJN0', BASE='https://www.amazon.co.uk'
function extract(html:string):Item[]{const doc=new DOMParser().parseFromString(html,'text/html'),out:Item[]=[];for(const card of Array.from(doc.querySelectorAll('[data-asin]'))){const asin=(card.getAttribute('data-asin')||'').trim();if(!/^[A-Z0-9]{10}$/.test(asin))continue;const title=(card.querySelector('h2 span')?.textContent||card.querySelector('h2')?.textContent||'Amazon product').trim(),price=(card.querySelector('.a-price .a-offscreen')?.textContent||'').trim(),a=card.querySelector('h2 a') as HTMLAnchorElement|null,href=a?.getAttribute('href')||('/dp/'+asin);out.push({asin,title,price,url:href.startsWith('http')?href:BASE+href})}return Array.from(new Map(out.map(x=>[x.asin,x])).values())}
export default function AmazonImporter(){
 const [pages,setPages]=useState<Record<number,Item[]>>({}),[page,setPage]=useState(1),[raw,setRaw]=useState(''),[msg,setMsg]=useState('')
 const all=useMemo(()=>Array.from(new Map(Object.values(pages).flat().map(x=>[x.asin,x])).values()),[pages])
 const capture=()=>{const items=extract(raw);if(!items.length){setMsg('No Amazon product cards found. Copy the full page source.');return}setPages(v=>({...v,[page]:items}));setMsg('Captured '+items.length+' products from page '+page+'.');setRaw('')}
 const csv=()=>{const q=(s:string)=>'"'+String(s||'').replaceAll('"','""')+'"',rows=[['ASIN','Title','Price','Amazon URL'],...all.map(x=>[x.asin,x.title,x.price,x.url])],blob=new Blob([rows.map(r=>r.map(q).join(',')).join('\n')],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='flip-lead-amazon-storefront.csv';a.click();URL.revokeObjectURL(a.href)}
 const collector=`javascript:(async()=>{const seller='${SELLER}',market='A1F83G8C2ARO7P',sleep=ms=>new Promise(r=>setTimeout(r,ms)),items=new Map();let done=0;for(let p=1;p<=21;p++){document.title='Flip Lead: '+p+'/21 · '+items.size+' products';const u='https://www.amazon.co.uk/s?me='+seller+'&marketplaceID='+market+'&page='+p;try{const h=await fetch(u,{credentials:'include'}).then(r=>r.text()),d=new DOMParser().parseFromString(h,'text/html');d.querySelectorAll('[data-asin]').forEach(c=>{const asin=(c.getAttribute('data-asin')||'').trim();if(!/^[A-Z0-9]{10}$/.test(asin))return;const a=c.querySelector('a.a-link-normal[href*="/dp/"],h2 a')||c.querySelector('a[href*="/dp/"]'),href=a?.getAttribute('href')||('/dp/'+asin),img=c.querySelector('img.s-image')||c.querySelector('img'),title=(c.querySelector('[data-cy="title-recipe"] h2 span')?.textContent||c.querySelector('h2 span')?.textContent||c.querySelector('h2')?.textContent||img?.getAttribute('alt')||a?.getAttribute('aria-label')||'Amazon product').trim(),whole=(c.querySelector('.a-price-whole')?.textContent||'').replace(/[^0-9]/g,''),frac=(c.querySelector('.a-price-fraction')?.textContent||'').replace(/[^0-9]/g,''),off=(c.querySelector('.a-price .a-offscreen')?.textContent||c.querySelector('[data-a-color="price"] .a-offscreen')?.textContent||'').trim(),price=off||(whole?('£'+whole+'.'+(frac||'00')):'');items.set(asin,{asin,title,price,url:href.startsWith('http')?href:'https://www.amazon.co.uk'+href,page:p})});done=p;await sleep(900)}catch(e){alert('Stopped on page '+p+'. Amazon may have challenged the request. Captured '+items.size+' products.');break}}const rows=[['ASIN','Title','Price','Amazon URL','Page'],...Array.from(items.values()).map(x=>[x.asin,x.title,x.price,x.url,x.page])],q=s=>'"'+String(s||'').replaceAll('"','""')+'"',blob=new Blob([rows.map(r=>r.map(q).join(',')).join('\\n')],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='flip-lead-amazon-storefront-'+items.size+'-products.csv';a.click();URL.revokeObjectURL(a.href);document.title='Flip Lead: '+done+'/21 · '+items.size+' products';alert('Flip Lead captured '+items.size+' unique products across '+done+' page(s). CSV downloaded.');})()`
 const copyCollector=async()=>{try{await navigator.clipboard.writeText(collector);setMsg('Collector copied. Create a bookmark and paste it into the bookmark URL/address field.')}catch{setMsg('Browser blocked clipboard access. Select the collector code below and copy it manually.')}}
 return <main className="importPage"><div className="importTop"><div><small>AMAZON INTELLIGENCE</small><h1>Storefront Importer</h1><p>Capture all 21 seller pages, deduplicate ASINs and bring the catalogue into Flip Lead.</p></div><Link href="/">← Flip Lead</Link></div>
 <section className="importCard"><div className="store"><b>Storefront</b><span>Seller {SELLER}</span><a href={BASE+'/s?me='+SELLER+'&marketplaceID=A1F83G8C2ARO7P'} target="_blank">Open Amazon storefront ↗</a></div>
 <div className="bulk"><small>FASTEST METHOD</small><h2>21-page browser collector</h2><p>Amazon blocks our server from crawling the storefront, so this collector runs inside your own Amazon tab. It requests pages 1–21, extracts ASINs plus titles from multiple Amazon title/image fields and prices from both hidden and split price markup, removes duplicate ASINs and downloads one CSV.</p><div className="actions"><button onClick={copyCollector}>Copy updated 21-page collector</button></div><ol><li>Click <b>Copy 21-page collector</b>.</li><li>Create any new bookmark in Edge.</li><li>Edit that bookmark and replace its URL with the copied collector.</li><li>Open the Amazon storefront, then click your new bookmark.</li><li>Leave that tab open while its title shows progress such as <b>Flip Lead: 8/21 · 126 products</b>.</li></ol><details><summary>Show collector code</summary><textarea readOnly value={collector}/></details></div>{msg&&<p className="message">{msg}</p>}</section>
 <section className="importCard"><div className="steps"><small>FALLBACK</small><h2>Manual page capture</h2><p>If Amazon challenges the bulk collector, the original method remains available: View page source, copy the HTML, paste it here and capture each page.</p></div><div className="captureRow"><label><span>PAGE</span><input type="number" min="1" max="99" value={page} onChange={e=>setPage(Number(e.target.value)||1)}/></label><div className="progress"><span>PAGES CAPTURED</span><b>{Object.keys(pages).length} / 21</b></div><div className="progress"><span>UNIQUE PRODUCTS</span><b>{all.length}</b></div></div><textarea value={raw} onChange={e=>setRaw(e.target.value)} placeholder="Paste Amazon page HTML here…"/><div className="actions"><button onClick={capture}>Capture page {page}</button><button className="secondary" disabled={!all.length} onClick={csv}>Export {all.length} products CSV</button><button className="secondary" onClick={()=>{setPages({});setMsg('Importer cleared.')}}>Clear</button></div></section>
 <section className="importCard"><div className="resultHead"><div><small>MANUAL CAPTURE CATALOGUE</small><h2>{all.length} unique products</h2></div><span>{Object.keys(pages).sort((a,b)=>Number(a)-Number(b)).map(n=>'Page '+n).join(' · ')||'No manual pages captured yet'}</span></div>{!all.length?<div className="empty">Manual captures appear here. The bulk collector downloads its own complete CSV.</div>:<div className="importTable"><table><thead><tr><th>ASIN</th><th>Product</th><th>Price</th><th>Amazon</th></tr></thead><tbody>{all.map(x=><tr key={x.asin}><td><b>{x.asin}</b></td><td>{x.title}</td><td>{x.price||'—'}</td><td><a href={x.url} target="_blank">Open ↗</a></td></tr>)}</tbody></table></div>}</section>
 <style jsx>{`.importPage{max-width:1180px;margin:auto;padding:40px 24px;color:#0B1320}.importTop,.store,.resultHead{display:flex;justify-content:space-between;gap:20px;align-items:flex-start}.importTop small,.resultHead small,.bulk small,.steps small{color:#21C784;font-weight:900;letter-spacing:.12em}.importTop h1{font-size:36px;margin:7px 0}.importTop p,.bulk p,.steps p{color:#647084;max-width:760px;line-height:1.6}.importTop>a,.store a,td a{color:#1E66F5;font-weight:800;text-decoration:none}.importCard{background:white;border:1px solid #DDE3EA;border-radius:14px;padding:22px;margin-top:20px}.store{align-items:center;padding-bottom:18px;border-bottom:1px solid #DDE3EA}.store span{color:#647084}.bulk{padding-top:20px}.bulk h2,.steps h2{margin:6px 0}.bulk ol{line-height:1.8;color:#475569}.bulk details{margin-top:14px}.bulk details textarea{height:100px}.captureRow{display:grid;grid-template-columns:160px 1fr 1fr;gap:12px;margin-bottom:12px}.captureRow label,.progress{border:1px solid #DDE3EA;border-radius:10px;padding:12px}.captureRow span,.progress span{display:block;font-size:10px;color:#647084;font-weight:800}.captureRow input{border:0;font-size:20px;font-weight:800;width:100%;outline:none}.progress b{display:block;font-size:22px;margin-top:5px}textarea{box-sizing:border-box;width:100%;height:210px;border:1px solid #DDE3EA;border-radius:10px;padding:13px;font:12px monospace;resize:vertical}.actions{display:flex;gap:8px;margin-top:12px;flex-wrap:wrap}.actions button{border:0;border-radius:8px;background:#1E66F5;color:white;padding:10px 14px;font-weight:800;cursor:pointer}.actions .secondary{background:#EEF2F7;color:#0B1320}.actions button:disabled{opacity:.45}.message{font-size:12px;color:#647084}.resultHead h2{margin:5px 0}.resultHead>span{font-size:11px;color:#647084}.empty{padding:30px;background:#F2F4F7;border-radius:10px;color:#647084}.importTable{overflow:auto}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:11px;border-bottom:1px solid #E8ECF1;font-size:12px}th{font-size:10px;color:#647084}@media(max-width:700px){.importTop,.store,.resultHead{flex-direction:column}.store{align-items:flex-start}.captureRow{grid-template-columns:1fr}.importPage{padding:24px 12px}.importTop h1{font-size:29px}}`}</style></main>
}