'use client'
import {useEffect,useRef,useState} from 'react'
import {BrowserMultiFormatOneDReader,IBrowserCodeReaderControls} from '@zxing/browser'
import {BarcodeFormat,DecodeHintType} from '@zxing/library'
type Scan={barcode:string;quantity:number;name:string;brand?:string;size?:string;asin?:string;source?:string;status?:string;scannedAt:string}
type Mode='unique'|'count'
const esc=(v:any)=>'"'+String(v??'').replace(/"/g,'""')+'"'
export default function MobileBarcode(){
 const [rows,setRows]=useState<Scan[]>([]),[manual,setManual]=useState(''),[running,setRunning]=useState(false),[msg,setMsg]=useState('Ready to scan'),[mode,setMode]=useState<Mode>('unique'),[flash,setFlash]=useState(false),[torch,setTorch]=useState(false),[torchOK,setTorchOK]=useState(false),[zoomOK,setZoomOK]=useState(false),[zoom,setZoom]=useState(1)
 const video=useRef<HTMLVideoElement>(null),controls=useRef<IBrowserCodeReaderControls|null>(null),rowsRef=useRef<Scan[]>([]),modeRef=useRef<Mode>('unique'),last=useRef<{code:string,time:number}>({code:'',time:0}),track=useRef<MediaStreamTrack|null>(null),wantedRunning=useRef(false),restarting=useRef(false)
 const persist=(next:Scan[])=>{rowsRef.current=next;setRows(next);localStorage.setItem('source-stack-warehouse-scans',JSON.stringify(next))}
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('source-stack-warehouse-scans')||'[]');rowsRef.current=saved;setRows(saved);const m=(localStorage.getItem('source-stack-scan-mode') as Mode)||'unique';modeRef.current=m;setMode(m)}catch{};const wake=()=>{if(document.visibilityState==='visible'&&wantedRunning.current&&!track.current){setMsg('Resuming scanner…');restarting.current=false;void start()}};document.addEventListener('visibilitychange',wake);return()=>{document.removeEventListener('visibilitychange',wake);wantedRunning.current=false;controls.current?.stop()}},[])
 const feedback=()=>{setFlash(true);setTimeout(()=>setFlash(false),120);navigator.vibrate?.(35);try{const A=(window.AudioContext||(window as any).webkitAudioContext);const a=new A(),o=a.createOscillator(),g=a.createGain();o.frequency.value=1050;g.gain.value=.045;o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+.055)}catch{}}
 const lookup=async(barcode:string)=>{try{const cache=JSON.parse(localStorage.getItem('source-stack-barcode-cache')||'{}');if(cache[barcode]){applyLookup(barcode,cache[barcode]);return}const d=await fetch('/api/barcode-lookup?barcode='+encodeURIComponent(barcode),{cache:'no-store'}).then(r=>r.json());const m=d.match||null;if(m){cache[barcode]=m;localStorage.setItem('source-stack-barcode-cache',JSON.stringify(cache))}applyLookup(barcode,m)}catch{applyLookup(barcode,null)}}
 const applyLookup=(barcode:string,m:any)=>{const next=rowsRef.current.map(x=>x.barcode===barcode?{...x,name:m?.name||'Unknown product',brand:m?.brand||'',size:m?.size||'',asin:m?.asin||'',source:m?.source||'',status:m?.confidence||'NEEDS REVIEW'}:x);persist(next);if(m)setMsg('✓ '+m.name)}
 const add=(raw:string)=>{const barcode=raw.replace(/\D/g,'');if(!/^\d{8,14}$/.test(barcode)){setMsg('Barcode must be 8–14 digits');return}const now=Date.now();if(last.current.code===barcode&&now-last.current.time<1200)return;last.current={code:barcode,time:now};const current=rowsRef.current,found=current.find(x=>x.barcode===barcode);if(found){const qty=modeRef.current==='count'?found.quantity+1:found.quantity;const next=current.map(x=>x.barcode===barcode?{...x,quantity:qty,scannedAt:new Date().toISOString()}:x);persist(next);feedback();setMsg(modeRef.current==='count'?'✓ '+(found.name||barcode)+' · '+qty:'✓ Already captured · '+(found.name||barcode));return}const pending:Scan={barcode,quantity:1,name:'Identifying…',status:'LOOKUP',scannedAt:new Date().toISOString()};persist([pending,...current]);setManual('');feedback();setMsg('✓ Captured '+barcode);void lookup(barcode)}
 const stop=()=>{wantedRunning.current=false;controls.current?.stop();controls.current=null;track.current=null;setRunning(false);setTorch(false);setTorchOK(false);setZoomOK(false)}
 const start=async()=>{if(restarting.current)return;restarting.current=true;wantedRunning.current=true;try{const hints=new Map();hints.set(DecodeHintType.POSSIBLE_FORMATS,[BarcodeFormat.EAN_13,BarcodeFormat.EAN_8,BarcodeFormat.UPC_A,BarcodeFormat.UPC_E]);const reader=new BrowserMultiFormatOneDReader(hints);setRunning(true);setMsg('Scanning · centre the barcode');controls.current=await reader.decodeFromConstraints({audio:false,video:{facingMode:{ideal:'environment'},width:{ideal:960},height:{ideal:540},frameRate:{ideal:30,max:30}}},video.current!,(result)=>{const code=result?.getText();if(code)add(code)});const s=video.current?.srcObject as MediaStream|null;track.current=s?.getVideoTracks()[0]||null;const caps=(track.current?.getCapabilities?.()||{}) as any;setTorchOK(!!caps.torch);setZoomOK(!!caps.zoom);if(track.current){const advanced:any[]=[];if(caps.focusMode?.includes?.('continuous'))advanced.push({focusMode:'continuous'});if(advanced.length)track.current.applyConstraints({advanced}).catch(()=>{})}if(track.current){track.current.onended=()=>{if(wantedRunning.current){setMsg('Camera paused · restarting…');setTimeout(()=>{restarting.current=false;void start()},400)}}}restarting.current=false}catch(e:any){restarting.current=false;setRunning(false);setMsg(e?.message||'Camera scanner unavailable')}}
 const toggleTorch=async()=>{if(!track.current)return;const next=!torch;try{await track.current.applyConstraints({advanced:[{torch:next} as any]});setTorch(next)}catch{}}\n const setCameraZoom=async(v:number)=>{if(!track.current)return;const caps=(track.current.getCapabilities?.()||{}) as any;if(!caps.zoom)return;const z=Math.max(caps.zoom.min||1,Math.min(caps.zoom.max||v,v));try{await track.current.applyConstraints({advanced:[{zoom:z} as any]});setZoom(z)}catch{}}\n const refocus=async()=>{if(!track.current)return;const caps=(track.current.getCapabilities?.()||{}) as any;try{if(caps.focusMode?.includes?.('single-shot'))await track.current.applyConstraints({advanced:[{focusMode:'single-shot'} as any]});else if(caps.focusMode?.includes?.('continuous'))await track.current.applyConstraints({advanced:[{focusMode:'continuous'} as any]});setMsg('Refocused · hold barcode inside guide')}catch{setMsg('Move slightly back and tilt package to reduce glare')}}
 const changeMode=(m:Mode)=>{modeRef.current=m;setMode(m);localStorage.setItem('source-stack-scan-mode',m)}
 const update=(barcode:string,patch:Partial<Scan>)=>persist(rowsRef.current.map(x=>x.barcode===barcode?{...x,...patch}:x))
 const csv=()=>{const head=['barcode','quantity','product_name','brand','size','asin','lookup_source','match_status','scanned_at'];const body=rowsRef.current.map(x=>[x.barcode,x.quantity,x.name,x.brand,x.size,x.asin,x.source,x.status,x.scannedAt].map(esc).join(','));const blob=new Blob([[head.join(','),...body].join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='source-stack-warehouse-barcodes.csv';a.click();URL.revokeObjectURL(a.href)}
 return <main style={{maxWidth:720,margin:'0 auto',padding:14,fontFamily:'Arial,sans-serif',background:flash?'#d9ffe9':'#f5f7fb',minHeight:'100vh',transition:'background .1s'}}>
  <header style={{marginBottom:12}}><small style={{fontWeight:800,letterSpacing:2,color:'#00a86b'}}>SOURCE STACK · RAPID SCAN</small><h1 style={{margin:'5px 0'}}>Warehouse Scanner</h1><p style={{color:'#536070',margin:'5px 0'}}>Scan first. Identification happens in the background.</p></header>
  <section style={{background:'white',border:'1px solid #dce3ed',borderRadius:18,padding:12}}>
   <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8,marginBottom:10}}><button onClick={()=>changeMode('unique')} style={{padding:11,borderRadius:10,border:mode==='unique'?'2px solid #2468f2':'1px solid #ccd5e1',fontWeight:800}}>Unique products</button><button onClick={()=>changeMode('count')} style={{padding:11,borderRadius:10,border:mode==='count'?'2px solid #2468f2':'1px solid #ccd5e1',fontWeight:800}}>Stock count</button></div>
   <div onClick={refocus} style={{position:'relative',display:running?'block':'none',touchAction:'manipulation'}}><video ref={video} playsInline muted style={{width:'100%',aspectRatio:'16/9',objectFit:'cover',background:'#111827',borderRadius:14}}/><div style={{position:'absolute',left:'7%',right:'7%',top:'37%',height:72,border:'3px solid #35e59a',borderRadius:12}}/><div style={{position:'absolute',left:'10%',right:'10%',top:'50%',height:2,background:'#35e59a'}}/><div style={{position:'absolute',bottom:8,left:8,right:8,textAlign:'center',color:'white',fontSize:12,fontWeight:800,textShadow:'0 1px 3px #000'}}>Tap to refocus · for glare, tilt the pack 10–20°</div></div>
   <div style={{display:'flex',gap:8,marginTop:running?10:0}}><button onClick={running?stop:start} style={{flex:1,padding:15,border:0,borderRadius:12,background:'#2468f2',color:'white',fontWeight:800,fontSize:17}}>{running?'Stop scanner':'Start rapid scan'}</button>{running&&torchOK&&<button onClick={toggleTorch} style={{padding:'0 16px',borderRadius:12,border:'1px solid #ccd5e1',fontWeight:800}}>{torch?'Torch off':'Torch'}</button>}</div>{running&&zoomOK&&<div style={{display:'flex',gap:8,alignItems:'center',marginTop:8}}><span style={{fontSize:12,fontWeight:800}}>ZOOM</span><button onClick={()=>setCameraZoom(1)} style={{flex:1,padding:9}}>1×</button><button onClick={()=>setCameraZoom(1.5)} style={{flex:1,padding:9}}>1.5×</button><button onClick={()=>setCameraZoom(2)} style={{flex:1,padding:9}}>2×</button><span style={{fontSize:12}}>{zoom.toFixed(1)}×</span></div>}
   <p style={{fontWeight:800,minHeight:20}}>{msg}</p>
   <div style={{display:'flex',gap:8}}><input inputMode="numeric" value={manual} onChange={e=>setManual(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')add(manual)}} placeholder="Manual EAN / UPC" style={{flex:1,padding:13,border:'1px solid #ccd5e1',borderRadius:10,fontSize:16}}/><button onClick={()=>add(manual)} style={{padding:'0 18px',borderRadius:10,border:'1px solid #ccd5e1',fontWeight:800}}>Add</button></div>
  </section>
  <section style={{marginTop:12,background:'white',border:'1px solid #dce3ed',borderRadius:18,padding:14}}>
   <div style={{display:'flex',justifyContent:'space-between',gap:10,alignItems:'center'}}><div><small>SESSION</small><h2 style={{margin:'3px 0'}}>{rows.length} products · {rows.reduce((a,x)=>a+x.quantity,0)} items</h2></div><button disabled={!rows.length} onClick={csv}>Export CSV</button></div>
   {rows.slice(0,30).map(x=><div key={x.barcode} style={{padding:'11px 0',borderTop:'1px solid #edf0f4'}}><b>{x.barcode}</b><div style={{fontWeight:700}}>{x.name||'Unknown product'}{x.brand?' · '+x.brand:''}{x.size?' · '+x.size:''}</div><small>{x.source||'Looking up…'}{x.asin?' · ASIN '+x.asin:''}</small><div style={{display:'grid',gridTemplateColumns:'75px 1fr 36px',gap:6,marginTop:6}}><input type="number" min="1" value={x.quantity} onChange={e=>update(x.barcode,{quantity:Math.max(1,Number(e.target.value)||1)})}/><input value={x.name} onChange={e=>update(x.barcode,{name:e.target.value})}/><button onClick={()=>persist(rowsRef.current.filter(r=>r.barcode!==x.barcode))}>×</button></div></div>)}
   {rows.length>30&&<p><b>+ {rows.length-30} more saved in this session.</b> All rows are included in CSV export.</p>}
   {!rows.length&&<p style={{color:'#6b7280'}}>No products captured yet.</p>}
  </section>
 </main>
}