'use client'
import {useEffect,useRef,useState} from 'react'
import {BrowserMultiFormatOneDReader,IBrowserCodeReaderControls} from '@zxing/browser'
import {BarcodeFormat,DecodeHintType} from '@zxing/library'
type Scan={barcode:string;quantity:number;name:string;brand?:string;size?:string;asin?:string;source?:string;status?:string;scannedAt:string}
const esc=(v:any)=>'"'+String(v??'').replace(/"/g,'""')+'"'
export default function MobileBarcode(){
 const [rows,setRows]=useState<Scan[]>([]),[manual,setManual]=useState(''),[running,setRunning]=useState(false),[msg,setMsg]=useState('Ready to scan')
 const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),timer=useRef<any>(null),last=useRef(''),controls=useRef<IBrowserCodeReaderControls|null>(null)
 useEffect(()=>{try{setRows(JSON.parse(localStorage.getItem('source-stack-warehouse-scans')||'[]'))}catch{};return stop},[])
 const save=(next:Scan[])=>{setRows(next);localStorage.setItem('source-stack-warehouse-scans',JSON.stringify(next))}
 const add=async(raw:string)=>{const barcode=raw.replace(/\\s/g,'');if(!/^\\d{8,14}$/.test(barcode)){setMsg('Barcode must be 8–14 digits');return}const now=new Date().toISOString();const found=rows.find(x=>x.barcode===barcode);if(found){save(rows.map(x=>x.barcode===barcode?{...x,quantity:x.quantity+1,scannedAt:now}:x));setMsg('✓ '+(found.name||barcode)+' · '+(found.quantity+1));if(navigator.vibrate)navigator.vibrate(45);return}const pending:Scan={barcode,quantity:1,name:'Looking up…',status:'LOOKUP',scannedAt:now};save([pending,...rows]);setManual('');setMsg('Barcode captured · identifying…');if(navigator.vibrate)navigator.vibrate(45);try{const d=await fetch('/api/barcode-lookup?barcode='+encodeURIComponent(barcode),{cache:'no-store'}).then(r=>r.json());const m=d.match;setRows(prev=>{const next=prev.map(x=>x.barcode===barcode?{...x,name:m?.name||'Unknown product',brand:m?.brand||'',size:m?.size||'',asin:m?.asin||'',source:m?.source||'',status:m?.confidence||'NEEDS REVIEW'}:x);localStorage.setItem('source-stack-warehouse-scans',JSON.stringify(next));return next});setMsg(m?'✓ '+m.name:'Captured · product not found')}catch{setMsg('Captured · lookup unavailable')}}
 const stop=()=>{controls.current?.stop();controls.current=null;if(timer.current)clearInterval(timer.current);timer.current=null;stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;setRunning(false)}
 const start=async()=>{try{const hints=new Map();hints.set(DecodeHintType.POSSIBLE_FORMATS,[BarcodeFormat.EAN_13,BarcodeFormat.EAN_8,BarcodeFormat.UPC_A,BarcodeFormat.UPC_E]);hints.set(DecodeHintType.TRY_HARDER,true);const reader=new BrowserMultiFormatOneDReader(hints);setRunning(true);setMsg('Scanning… fill the guide with the barcode');controls.current=await reader.decodeFromConstraints({audio:false,video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}}},video.current!,async(result)=>{const code=result?.getText();if(code&&code!==last.current){last.current=code;await add(code);setTimeout(()=>last.current='',650)}})}catch(e:any){setRunning(false);setMsg(e?.message||'Camera scanner unavailable')}}
 const update=(barcode:string,patch:Partial<Scan>)=>save(rows.map(x=>x.barcode===barcode?{...x,...patch}:x))
 const csv=()=>{const head=['barcode','quantity','product_name','brand','size','asin','lookup_source','match_status','scanned_at'];const body=rows.map(x=>[x.barcode,x.quantity,x.name,x.brand,x.size,x.asin,x.source,x.status,x.scannedAt].map(esc).join(','));const blob=new Blob([[head.join(','),...body].join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='source-stack-warehouse-barcodes.csv';a.click();URL.revokeObjectURL(a.href)}
 return <main style={{maxWidth:720,margin:'0 auto',padding:18,fontFamily:'Arial,sans-serif',background:'#f5f7fb',minHeight:'100vh'}}>
  <header style={{marginBottom:18}}><small style={{fontWeight:800,letterSpacing:2,color:'#00a86b'}}>SOURCE STACK · MOBILE</small><h1 style={{margin:'6px 0'}}>Warehouse Barcode Capture</h1><p style={{color:'#536070'}}>Scan physical stock first. Export and verify before anything is written to the live product database.</p></header>
  <section style={{background:'white',border:'1px solid #dce3ed',borderRadius:18,padding:16}}>
   <div style={{position:'relative',display:running?'block':'none'}}><video ref={video} playsInline muted style={{width:'100%',aspectRatio:'4/3',objectFit:'cover',background:'#111827',borderRadius:14}}/><div style={{position:'absolute',left:'8%',right:'8%',top:'42%',height:70,border:'3px solid #35e59a',borderRadius:12,boxShadow:'0 0 0 999px rgba(0,0,0,.12)'}}/><div style={{position:'absolute',left:'12%',right:'12%',top:'50%',height:2,background:'#35e59a'}}/></div>
   <button onClick={running?stop:start} style={{width:'100%',padding:16,border:0,borderRadius:12,background:'#2468f2',color:'white',fontWeight:800,fontSize:17,marginTop:running?12:0}}>{running?'Stop camera':'Scan barcode with camera'}</button>
   <p style={{fontWeight:700}}>{msg}</p>
   <div style={{display:'flex',gap:8}}><input inputMode="numeric" value={manual} onChange={e=>setManual(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')add(manual)}} placeholder="Or enter EAN / UPC" style={{flex:1,padding:14,border:'1px solid #ccd5e1',borderRadius:10,fontSize:16}}/><button onClick={()=>add(manual)} style={{padding:'0 18px',borderRadius:10,border:'1px solid #ccd5e1',fontWeight:800}}>Add</button></div>
  </section>
  <section style={{marginTop:16,background:'white',border:'1px solid #dce3ed',borderRadius:18,padding:16}}>
   <div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><small>CAPTURED STOCK</small><h2 style={{margin:'4px 0'}}>{rows.length} unique barcodes · {rows.reduce((a,x)=>a+x.quantity,0)} items</h2></div><button disabled={!rows.length} onClick={csv}>Export CSV</button></div>
   {rows.map(x=><div key={x.barcode} style={{padding:'14px 0',borderTop:'1px solid #edf0f4'}}><b>{x.barcode}</b><div style={{marginTop:4,fontWeight:700}}>{x.name||'Unknown product'}{x.brand?' · '+x.brand:''}{x.size?' · '+x.size:''}</div><small>{x.source||'Pending lookup'}{x.asin?' · ASIN '+x.asin:''}</small><div style={{display:'grid',gridTemplateColumns:'90px 1fr 36px',gap:8,marginTop:8}}><input type="number" min="1" value={x.quantity} onChange={e=>update(x.barcode,{quantity:Math.max(1,Number(e.target.value)||1)})}/><input value={x.name} onChange={e=>update(x.barcode,{name:e.target.value})} placeholder="Product name (optional)"/><button onClick={()=>save(rows.filter(r=>r.barcode!==x.barcode))}>×</button></div></div>)}
   {!rows.length&&<p style={{color:'#6b7280'}}>Nothing scanned yet. Each repeat scan increases the quantity instead of creating another row.</p>}
  </section>
 </main>
}
