const s=document.querySelector('#s');
async function status(){const x=await chrome.storage.local.get(['flItems','flScan','flEnrich','flScout']);const items=Object.values(x.flItems||{}),n=items.length,e=items.filter(i=>i.ean||i.upc||i.gtin).length,scout=Object.values(x.flScout?.items||{}).length;if(x.flScan?.active)s.textContent='Storefront scan: page '+(x.flScan.page||1)+'/21 · '+n+' products';else if(x.flEnrich?.active)s.textContent='Enriching '+(x.flEnrich.index+1)+'/'+n+' · '+e+' with identifiers';else s.textContent='Captured: '+n+' products · '+e+' with barcode/GTIN'+(scout?' · Scout '+scout:'')}
async function active(){return (await chrome.tabs.query({active:true,currentWindow:true}))[0]}
document.querySelector('#start').onclick=async()=>{const tab=await active();if(!tab?.id)return;s.textContent='Starting storefront scan…';chrome.tabs.sendMessage(tab.id,{type:'FL_START'});setTimeout(status,500)};
document.querySelector('#scout').onclick=async()=>{const tab=await active();if(!tab?.id||!/^https:\/\/www\.amazon\.co\.uk\/s(?:[/?]|$)/.test(tab.url||'')){s.textContent='Open the Amazon seller storefront first.';return}s.textContent='Starting Storefront Scout…';chrome.tabs.sendMessage(tab.id,{type:'FL_SCOUT_START'},res=>{if(chrome.runtime.lastError){s.textContent='Scout failed. Reload the extension and storefront, then retry.';return}setTimeout(status,500)})};
document.querySelector('#enrich').onclick=async()=>{const x=await chrome.storage.local.get('flItems'),items=Object.values(x.flItems||{});if(!items.length){s.textContent='Scan the storefront first.';return}await chrome.storage.local.set({flEnrich:{active:true,index:0,total:items.length,returnUrl:(await active())?.url||''}});const tab=await active();await chrome.tabs.update(tab.id,{url:'https://www.amazon.co.uk/dp/'+items[0].asin})};
document.querySelector('#diagnostic').onclick=async()=>{const tab=await active();if(!tab?.id||!/amazon\.co\.uk\/.+\/dp\/|amazon\.co\.uk\/dp\//.test(tab.url||'')){s.textContent='Open an Amazon product /dp/ page first.';return}s.textContent='Inspecting this product page…';chrome.tabs.sendMessage(tab.id,{type:'FL_DIAGNOSTIC'},res=>{if(chrome.runtime.lastError||!res?.diagnostic){s.textContent='Diagnostic failed. Reload the extension and product page, then retry.';return}const d=res.diagnostic,blob='data:application/json;charset=utf-8,'+encodeURIComponent(JSON.stringify(d,null,2));chrome.downloads.download({url:blob,filename:'flip-lead-amazon-diagnostic-'+(d.asin||'product')+'.json',saveAs:true});s.textContent='Diagnostic captured for '+(d.asin||'product')+' · '+d.identifierRows.length+' identifier rows.'})};
document.querySelector('#exportScout').onclick=async()=>{const x=await chrome.storage.local.get('flScout'),sc=x.flScout;if(!sc?.items){s.textContent='Run Storefront Scout first.';return}const items=Object.values(sc.items).sort((a,b)=>a.storefrontPosition-b.storefrontPosition),q=v=>'"'+String(v??'').replaceAll('"','""')+'"',csv=[['Storefront Position','ASIN','Title','Price','Sort Mode','Page','Amazon URL','Captured At'],...items.map(x=>[x.storefrontPosition,x.asin,x.title,x.price,x.sortMode,x.page,x.url,x.capturedAt])].map(r=>r.map(q).join(',')).join('\n');chrome.downloads.download({url:'data:text/csv;charset=utf-8,'+encodeURIComponent(csv),filename:'flip-lead-storefront-scout-'+(sc.sortMode||'current-order').replace(/[^a-z0-9]+/gi,'-').toLowerCase()+'-'+items.length+'.csv',saveAs:true})};
document.querySelector('#export').onclick=async()=>{const x=await chrome.storage.local.get('flItems'),items=Object.values(x.flItems||{}),q=v=>'"'+String(v??'').replaceAll('"','""')+'"',csv=[['ASIN','Title','Price','EAN','UPC','GTIN','Amazon URL','Page'],...items.map(x=>[x.asin,x.title,x.price,x.ean||'',x.upc||'',x.gtin||'',x.url,x.page])].map(r=>r.map(q).join(',')).join('\n');chrome.downloads.download({url:'data:text/csv;charset=utf-8,'+encodeURIComponent(csv),filename:'flip-lead-amazon-enriched-'+items.length+'-products.csv',saveAs:true})};
document.querySelector('#clear').onclick=async()=>{await chrome.storage.local.remove(['flItems','flScan','flEnrich','flDiagnostic','flScout']);status()};status();