'use client'
import {useMemo,useState} from 'react'
import {BarChart3,BookOpen,Calculator,LayoutDashboard,Settings,ShoppingBag,Truck,Zap} from 'lucide-react'
type Row={id:string;product:string;ean:string;supplier:string;buy:number;sell:number;qty:number;status:string;decision:string;actualSell?:number}
const seed:Row[]=[
{id:'1',product:"Reese's Pieces Theatre Box 113g",ean:'034000470772',supplier:'American Fizz',buy:1.95,sell:5.99,qty:24,status:'Completed',decision:'BUY',actualSell:5.75},
{id:'2',product:'ThinkPad Thunderbolt 3 Dock Gen 2',ean:'0193386053798',supplier:'Tech Clearance Co',buy:42,sell:89.99,qty:6,status:'Selling',decision:'BUY'},
{id:'3',product:'Jabra Evolve2 40 SE',ean:'5706991028090',supplier:'Office Outlet',buy:38.5,sell:69.99,qty:4,status:'Analysed',decision:'TEST BUY'}]
const gbp=(n:number)=>'£'+n.toFixed(2)
export default function Page(){
 const [view,setView]=useState('Overview'); const [rows,setRows]=useState(seed)
 const [rules,setRules]=useState({roi:30,profit:2,margin:15,maxCapital:500,firstCapital:350,firstUnits:24})
 const [budget,setBudget]=useState(2000)
 const [a,setA]=useState({product:'Anker USB-C Hub 7-in-1',ean:'0194644020347',supplier:'Liquidation World',buy:12,sell:29.99,fees:4.5,fulfilment:3.49,pack:0.5,qty:24,source:'Manual Estimate'})
 const calc=useMemo(()=>{const profit=a.sell-a.buy-a.fees-a.fulfilment-a.pack,roi=profit/a.buy*100,margin=profit/a.sell*100,capital=a.buy*a.qty;return{profit,roi,margin,capital,revenue:a.sell*a.qty}},[a])
 const seen=rows.find(r=>r.ean===a.ean); const hard=calc.roi>=rules.roi&&calc.profit>=rules.profit&&calc.margin>=rules.margin&&calc.capital<=rules.maxCapital
 const exposure=calc.capital<=rules.firstCapital&&a.qty<=rules.firstUnits
 const decision=hard&&exposure&&a.source!=='Manual Estimate'?'BUY':calc.roi>=rules.roi&&calc.profit>=rules.profit?'TEST BUY':calc.profit>0?'CONSIDER':'WALK AWAY'
 const save=()=>{setRows([{id:String(Date.now()),product:a.product,ean:a.ean,supplier:a.supplier,buy:a.buy,sell:a.sell,qty:a.qty,status:'Analysed',decision},...rows]);setView('Stock Memory')}
 const purchase=(id:string)=>setRows(rows.map(r=>r.id===id?{...r,status:'Purchased'}:r))
 const complete=(id:string)=>setRows(rows.map(r=>r.id===id?{...r,status:'Completed',actualSell:r.sell*.96}:r))
 const active=rows.filter(r=>['Purchased','Selling'].includes(r.status)).reduce((s,r)=>s+r.buy*r.qty,0)
 const realised=rows.filter(r=>r.status==='Completed').reduce((s,r)=>s+((r.actualSell||r.sell)-r.buy)*r.qty,0)
 const nav=[['Overview',LayoutDashboard],['New Analysis',Calculator],['Wholesale',ShoppingBag],['Opportunities',Zap],['Stock Memory',BookOpen],['Suppliers',Truck],['Portfolio',BarChart3],['Settings',Settings]] as const
 return <div className="shell"><aside><div className="brand"><b>S</b><strong>stockwise</strong></div><p className="tag">KNOW BEFORE YOU BUY.</p><nav>{nav.map(([n,I])=><button className={view===n?'active':''} onClick={()=>setView(n)} key={n}><I size={17}/>{n}</button>)}</nav><div className="user">MG <span>Matt · Trader</span></div></aside><main><header><span>Workspace / <b>{view}</b></span><i>V1.2</i></header><div className="page">
 {view==='Overview'&&<><Title k="PURCHASING INTELLIGENCE" t="Good afternoon, Matt." p="Know what deserves your capital before you place the order."/><div className="cards"><Metric l="Buying budget" v={gbp(budget-active)} s={gbp(active)+' committed'}/><Metric l="Active purchases" v={String(rows.filter(r=>['Purchased','Selling'].includes(r.status)).length)} s="currently in motion"/><Metric l="Realised profit" v={gbp(realised)} s="from completed outcomes"/><Metric l="Stock Memory" v={String(rows.length)} s="products remembered"/></div><section><h2>Recent opportunities</h2><Table rows={rows}/></section></>}
 {view==='New Analysis'&&<><Title k="BUYING" t="New Analysis" p="Run an opportunity through your rules before committing capital."/><div className="analysis"><section><h2>Opportunity details</h2><div className="grid">{Object.entries(a).map(([k,v])=>k==='source'?<label key={k}><span>Selling price source</span><select value={v as string} onChange={e=>setA({...a,source:e.target.value})}><option>Manual Estimate</option><option>Previous Actual Sale</option><option>Supplier RRP</option><option>Marketplace Research</option></select></label>:<label key={k}><span>{k==='ean'?'EAN / Barcode':k}</span><input value={v} type={typeof v==='number'?'number':'text'} onChange={e=>setA({...a,[k]:typeof v==='number'?Number(e.target.value):e.target.value})}/></label>)}</div><button className="primary" onClick={save}>Save to Stock Memory</button></section><section className="result"><span className={'decision '+decision.replace(' ','').toLowerCase()}>{decision}</span><h2>{gbp(calc.profit)} <small>profit / unit</small></h2><div className="resultgrid"><Metric l="ROI" v={calc.roi.toFixed(1)+'%'}/><Metric l="Margin" v={calc.margin.toFixed(1)+'%'}/><Metric l="Capital" v={gbp(calc.capital)}/><Metric l="Revenue" v={gbp(calc.revenue)}/></div>{a.source==='Manual Estimate'&&<div className="warn">UNVERIFIED selling-price assumption — strong economics can still result in TEST BUY.</div>}{seen&&<div className="memory">You’ve seen this EAN before: <b>{seen.product}</b> · previous decision {seen.decision}.</div>}</section></div></>}
 {view==='Opportunities'&&<><Title k="BUYING" t="Opportunities" p="Move analysed opportunities through the real purchase lifecycle."/><section><Table rows={rows} actions purchase={purchase} complete={complete}/></section></>}
 {view==='Stock Memory'&&<><Title k="MEMORY" t="Stock Memory" p="A calculator forgets. Stockwise remembers."/><section><Table rows={rows}/></section></>}
 {view==='Portfolio'&&<><Title k="INTELLIGENCE" t="Portfolio" p="Compare capital committed with what actually happened."/><div className="cards"><Metric l="Capital committed" v={gbp(active)}/><Metric l="Realised profit" v={gbp(realised)}/><Metric l="Units remembered" v={String(rows.reduce((s,r)=>s+r.qty,0))}/><Metric l="Completed outcomes" v={String(rows.filter(r=>r.status==='Completed').length)}/></div><section><h2>Expected vs actual</h2>{rows.filter(r=>r.status==='Completed').map(r=><div className="outcome" key={r.id}><b>{r.product}</b><span>Expected sell {gbp(r.sell)}</span><span>Actual avg {gbp(r.actualSell||r.sell)}</span></div>)}</section></>}
 {view==='Settings'&&<><Title k="SYSTEM" t="Buying Rules" p="These values drive Stockwise decisions."/><section><div className="grid">{Object.entries(rules).map(([k,v])=><label key={k}><span>{k}</span><input type="number" value={v} onChange={e=>setRules({...rules,[k]:Number(e.target.value)})}/></label>)}<label><span>Monthly buying budget</span><input type="number" value={budget} onChange={e=>setBudget(Number(e.target.value))}/></label></div></section></>}
 {view==='Wholesale'&&<><Title k="WHOLESALE OPPORTUNITIES" t="Find the products worth looking at." p="UPLOAD → MAP → ANALYSE → FILTER → INVESTIGATE → SHORTLIST → BUILD ORDER → REMEMBER"/><section className="drop"><ShoppingBag size={30}/><h2>Supplier catalogue workspace</h2><p>CSV/XLSX import, column mapping and catalogue delta are the next persistent-data milestone.</p><button className="primary">Upload catalogue</button></section></>}
 {view==='Suppliers'&&<><Title k="INTELLIGENCE" t="Suppliers" p="Learn from your own supplier history, not generic ratings."/><div className="cards">{[...new Set(rows.map(r=>r.supplier))].map(s=><Metric key={s} l={s} v={String(rows.filter(r=>r.supplier===s).length)} s="products analysed"/>)}</div></>}
 </div></main></div>}
function Title({k,t,p}:{k:string,t:string,p:string}){return <div className="title"><small>{k}</small><h1>{t}</h1><p>{p}</p></div>}
function Metric({l,v,s}:{l:string,v:string,s?:string}){return <div className="metric"><span>{l}</span><strong>{v}</strong>{s&&<small>{s}</small>}</div>}
function Table({rows,actions=false,purchase,complete}:{rows:Row[],actions?:boolean,purchase?:(x:string)=>void,complete?:(x:string)=>void}){return <div className="table"><table><thead><tr><th>Product</th><th>Supplier</th><th>Capital</th><th>Decision</th><th>Status</th>{actions&&<th>Next</th>}</tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b>{r.product}</b><small>{r.ean}</small></td><td>{r.supplier}</td><td>{gbp(r.buy*r.qty)}</td><td><span className={'pill '+r.decision.replace(' ','').toLowerCase()}>{r.decision}</span></td><td>{r.status}</td>{actions&&<td>{r.status==='Analysed'?<button onClick={()=>purchase?.(r.id)}>Mark purchased</button>:r.status!=='Completed'?<button onClick={()=>complete?.(r.id)}>Complete outcome</button>:<b>Remembered</b>}</td>}</tr>)}</tbody></table></div>}
