import {NextResponse} from 'next/server'
import {getSql} from '../../../lib/db'
import {parseCanonicalProduct,canonicalMatch} from '../../../lib/product-parser'
export const runtime='nodejs'; export const dynamic='force-dynamic'
const STOP=new Set(['case','pack','box','bag','can','candy','flavour','flavor','theatre','of','and','x','usa','us','american','wholesale'])
const norm=(s:any)=>String(s||'').toLowerCase().replace(/&amp;/g,'&').replace(/strawberries/g,'strawberry').replace(/&/g,' and ').replace(/[^a-z0-9.]+/g,' ').trim()
const toks=(s:any)=>norm(s).split(' ').filter((x:string)=>x.length>1&&!STOP.has(x)&&!/^\d/.test(x))
const set=(s:any)=>new Set(toks(s))
const sim=(a:any,b:any)=>{const A=set(a),B=set(b);if(!A.size||!B.size)return 0;let h=0;A.forEach(x=>{if(B.has(x))h++});return h/Math.max(A.size,B.size)}
function sizeMlG(s:any){const x=norm(s);let m=x.match(/(\d+(?:\.\d+)?)\s*(ml|g)\b/);if(m)return m[1]+m[2];m=x.match(/(\d+(?:\.\d+)?)\s*fl\s*oz/);if(m)return Math.round(Number(m[1])*29.5735)+'ml';m=x.match(/(\d+(?:\.\d+)?)\s*oz/);if(m)return Math.round(Number(m[1])*28.3495)+'g';return ''}
function canonicalBrand(o:any,id:any){const b=norm(o.brand);if(!b||b.includes('distribution')||b.includes('wholesale')||b.includes('glory')){const ib=norm(id.brand);return ib&&norm(o.product).includes(ib)?ib:''}return b}
function score(o:any,id:any,brands:string[],knowledge:any){
 const oe=String(o.ean||'').replace(/\D/g,''),ie=String(id.ean||'').replace(/\D/g,'')
 if(oe&&ie)return oe===ie?{score:100,band:'STRONG',reason:'Exact verified EAN / UPC'}:{score:0,band:'NO_MATCH',reason:'Barcode conflict'}
 const a=parseCanonicalProduct({title:o.product,brand:o.brand,size:o.size,caseQty:o.case_qty},brands,knowledge)
 const b=parseCanonicalProduct({title:id.product_name,brand:id.brand,size:id.unit_size||id.size,caseQty:1},brands,knowledge)
 const m=canonicalMatch(a,b); if(!m.match)return {score:m.score,band:'NO_MATCH',reason:m.reason,parsed:a}
 const band=m.score>=95?'STRONG':m.score>=75?'REVIEW':'WEAK'; return {score:m.score,band,reason:m.reason,parsed:a}
}
export async function GET(){try{const sql=getSql();const offers=await sql`SELECT s.name supplier,o.supplier_product_id,o.product,o.brand,o.size,o.case_qty,o.case_price,o.unit_cost,o.ean,o.country_origin FROM supplier_offers o JOIN suppliers s ON s.id=o.supplier_id LEFT JOIN product_identity_offers l ON l.supplier=s.name AND l.supplier_offer_id=o.supplier_product_id::text WHERE o.is_active=true AND l.supplier_offer_id IS NULL ORDER BY o.last_seen_at DESC LIMIT 1000`;const ids=await sql`SELECT id,product_name,brand,variant,size,unit_size,ean,asin,country_origin,status,canonical_key FROM master_product_identities ORDER BY updated_at DESC`;const brandAliases=await sql`SELECT canonical_brand,alias FROM product_brand_aliases`;const variantAliases=await sql`SELECT brand,canonical_variant,alias FROM product_variant_aliases`;const noiseTerms=await sql`SELECT term FROM product_noise_terms`;const rejected=await sql`SELECT supplier,supplier_offer_id,candidate_identity_id FROM identity_match_decisions WHERE decision='reject'`;const rej=new Set(rejected.map((x:any)=>x.supplier+'|'+x.supplier_offer_id+'|'+x.candidate_identity_id));const brands=[...ids.map((x:any)=>x.brand),...brandAliases.map((x:any)=>x.canonical_brand)].filter(Boolean);const aliasBrand=(v:any)=>{const z=norm(v);const a=brandAliases.find((x:any)=>norm(x.alias)===z);return a?.canonical_brand||v};const aliasVariant=(brand:any,v:any)=>{const z=norm(v);const a=variantAliases.find((x:any)=>norm(x.brand)===norm(brand)&&norm(x.alias)===z);return a?.canonical_variant||v};const knowledge={brandAliases,variantAliases,noiseTerms};const suggestions:any[]=[],newProducts:any[]=[];for(const o of offers){let best:any=null;for(const id of ids){if(rej.has(o.supplier+'|'+o.supplier_product_id+'|'+id.id))continue;const oo={...o,brand:aliasBrand(o.brand)};const ii={...id,brand:aliasBrand(id.brand),variant:aliasVariant(id.brand,id.variant)};const s=score(oo,ii,brands,knowledge);if(s.band==='NO_MATCH')continue;if(!best||s.score>best.score)best={...s,identity:id}}if(best&&best.score>=55)suggestions.push({offer:o,...best});else newProducts.push(o)}suggestions.sort((a,b)=>b.score-a.score);const strong=suggestions.filter(x=>x.band==='STRONG'),review=suggestions.filter(x=>x.band!=='STRONG');return NextResponse.json({ok:true,suggestions:suggestions.slice(0,500),strongCount:strong.length,reviewCount:review.length,newCount:newProducts.length,newProducts:newProducts.slice(0,500),unlinkedOffers:offers.length,identities:ids.length})}catch(e:any){return NextResponse.json({ok:false,error:e?.message||'Unable to build suggestions'},{status:500})}}
export async function POST(req:Request){try{const b=await req.json(),sql=getSql();if(!b.identityId||!b.supplier||!b.supplierOfferId)return NextResponse.json({ok:false,error:'Identity and supplier offer required'},{status:400});if(b.action==='reject'){await sql`INSERT INTO identity_match_decisions(identity_id,supplier,supplier_offer_id,candidate_identity_id,score,decision,reason) VALUES(NULL,${b.supplier},${String(b.supplierOfferId)},${Number(b.identityId)},${Number(b.score)||null},'reject',${b.reason||''})`;return NextResponse.json({ok:true})}await sql`INSERT INTO product_identity_offers(identity_id,supplier,supplier_offer_id,match_score,match_status,match_reason) VALUES(${Number(b.identityId)},${b.supplier},${String(b.supplierOfferId)},${Number(b.score)||null},'confirmed',${b.reason||''}) ON CONFLICT(supplier,supplier_offer_id) DO UPDATE SET identity_id=excluded.identity_id,match_score=excluded.match_score,match_status='confirmed',match_reason=excluded.match_reason,updated_at=now()`;await sql`INSERT INTO identity_match_decisions(identity_id,supplier,supplier_offer_id,candidate_identity_id,score,decision,reason) VALUES(${Number(b.identityId)},${b.supplier},${String(b.supplierOfferId)},${Number(b.identityId)},${Number(b.score)||null},'confirm',${b.reason||''})`;return NextResponse.json({ok:true})}catch(e:any){return NextResponse.json({ok:false,error:e?.message||'Unable to save match'},{status:500})}}