const DISTRIBUTOR=/distribution|wholesale|wando|spv services|a&a distribution|sweet\s*&?\s*glory|candy\s*cargo|global fmcg brands/i
export type CanonicalProduct={brand:string;brandSource:'supplied'|'alias'|'known-title'|'fallback';family:string;variant:string;unitSize:string;caseQty:number;consumerPackQty:number;canonicalKey:string;sizeConflict?:string}
export type ParserKnowledge={brandAliases?:any[];variantAliases?:any[];noiseTerms?:any[]}
const clean=(s:any)=>String(s||'').replace(/&amp;|&#x26;/gi,'&').replace(/&#x27;|&#039;|&apos;/gi,"'").replace(/&quot;|&#34;/gi,'"').replace(/\s+/g,' ').trim()
export const normalize=(s:any)=>clean(s).toLowerCase().replace(/\bjell[\s-]*o\b/g,'jello').replace(/\bair[\s-]*heads?\b/g,'airheads').replace(/\bcadburys\b/g,'cadbury').replace(/\bhershey(?:'s|s)\b/g,'hershey').replace(/\breese(?:'s|s)\b/g,'reese').replace(/strawberries/g,'strawberry').replace(/&/g,' and ').replace(/[^a-z0-9.]+/g,' ').replace(/\s+/g,' ').trim()
const phrase=(hay:string,needle:string)=>(' '+normalize(hay)+' ').includes(' '+normalize(needle)+' ')
export function cleanProductTitle(value:any){let s=clean(value);s=s.replace(/^\s*\[?\s*\d+\s*pack\s*\]?\s*/i,'').replace(/^\s*x\s*(\d+)\s+(?:box\s+of\s+)?/i,'').replace(/^\s*(\d+)\s*[x×]\s+(?=[A-Za-z])/i,'').replace(/^\s*pack\s+of\s+\d+\s*[-:]?\s*/i,'');s=s.replace(/^(?:new\s+)+/i,'').replace(/^\*{1,}\s*/,'').replace(/\*([^*]+)\*/g,'$1').replace(/\s+\*+\s*/g,' ').replace(/^price\s+inc(?:luding)?\s+sugar\s+tax\s+/i,'').replace(/^pack\s+size\s+\d+\s+/i,'').replace(/^model\s+\S+\s+/i,'').replace(/^brand:\s*[^:]+?\s+model:\s*\S+\s+/i,'').replace(/^model:\s*\S+\s+/i,'').replace(/^brand:\s*/i,'').replace(/^.*?popularity\s+alphabetical\s+alphabetical\s+reversed\s+latest\s+popularity\s+0\s+/i,'').replace(/^gen\.?\s+mills\s+/i,'General Mills ');s=s.replace(/\s+([,.;:!?])/g,'$1').replace(/([,.;:!?])(?!\s|$|\d)/g,'$1 ');s=s.split(/\s*[•]\s*|\.\s+(?=[A-Z])/)[0];s=s.replace(/\s+imported\s+from\s+[^.]+.*$/i,'').replace(/\s+wholesale\s+case\s+includes\s+.*$/i,'').replace(/\s+-\s+pack\s+of\s+(\d+)\s*x\s*([\d.]+\s*(?:kg|g|ml|l|fl\s*oz|oz))\b.*$/i,' - $1 x $2').replace(/\s+\((?:usa|china|canada|canadian|aus|australia)\)\s*/ig,' ').replace(/\s+bag\s+bag\b/ig,' Bag');return clean(s)}
const measure=(v:number,u:string)=>u==='kg'?{v:v*1000,u:'g'}:u==='gr'?{v,u:'g'}:u==='l'?{v:v*1000,u:'ml'}:{v,u}
function measureText(v:number,u:string){const m=measure(v,u);return (Number.isInteger(m.v)?m.v:Number(m.v.toFixed(2)))+m.u}
function allMeasures(v:any){const s=normalize(v),out:{v:number,u:string,text:string}[]=[];const re=/(\d+(?:\.\d+)?)\s*(kg|g|ml|l|fl\s*oz|fluid\s+ounces?|ounces?|oz)\b/g;let m;while((m=re.exec(s))){let n=Number(m[1]),u=m[2];if(u==='fl oz'||u.startsWith('fluid ounce')){n*=29.5735;u='ml'}else if(u==='oz'||u.startsWith('ounce')){n*=28.3495;u='g'}const z=measure(n,u);out.push({v:z.v,u:z.u,text:measureText(n,u)})}return out}
export function unitSize(size:any,title:any=''){const structured=allMeasures(size);if(structured.length)return structured[0].text;const ms=allMeasures(title);if(!ms.length)return '';const t=normalize(title);const explicit=t.match(/(?:each|per\s+(?:pack|bag|box|bottle|can))\D{0,12}(\d+(?:\.\d+)?)\s*(kg|g|ml|l|fl\s*oz|oz)\b/);if(explicit){let n=Number(explicit[1]),u=explicit[2];if(u==='fl oz'){n*=29.5735;u='ml'}else if(u==='oz'){n*=28.3495;u='g'}return measureText(n,u)}const x=t.match(/\b\d+\s*[x×]\s*(\d+(?:\.\d+)?)\s*(kg|g|ml|l|fl\s*oz|oz)\b/);if(x){let n=Number(x[1]),u=x[2];if(u==='fl oz'){n*=29.5735;u='ml'}else if(u==='oz'){n*=28.3495;u='g'}return measureText(n,u)}return ms[0].text}
function parseMeasure(s:string){const m=s.match(/^(\d+(?:\.\d+)?)(g|ml)$/);return m?{v:Number(m[1]),u:m[2]}:null}
function sizeEquivalent(a:string,b:string){if(!a||!b)return true;if(a===b)return true;const x=parseMeasure(a),y=parseMeasure(b);if(!x||!y||x.u!==y.u)return false;const tolerance=x.u==='g'?Math.max(1,Math.min(x.v,y.v)*0.015):Math.max(2,Math.min(x.v,y.v)*0.015);return Math.abs(x.v-y.v)<=tolerance}
function brandKey(v:string){return normalize(v)
 .replace(/\bair\s*heads?\b/g,'airheads')
 .replace(/\bairhead\b/g,'airheads')
 .replace(/\btwizzlers?\b/g,'twizzlers')
 .replace(/\bcadburys?\b/g,'cadbury')
 .replace(/\b([a-z0-9]+) s\b/g,'$1').trim()}
function brandEquivalent(a:string,b:string){const x=brandKey(a),y=brandKey(b);if(x===y)return true;return x.length>3&&y.length>3&&(x+'s'===y||y+'s'===x)}
function stripLeadingSalesNoise(v:string){return clean(v)
 .replace(/^\[\s*(\d+)\s*pack\s*\]\s*/i,'')
 .replace(/^\(?\s*(\d+)\s*[x×]\s+/i,'')
 .replace(/^[x×]\s*(\d+)\s+(?:boxes?\s+of\s+)?/i,'')
 .replace(/^\(?\s*pack\s+of\s+\d+\s*\)?\s*/i,'')
 .trim()}
export function consumerPackQty(title:string){const t=normalize(title);let m=t.match(/^\s*(?:\[\s*)?(\d+)\s*pack(?:\s*\])?\b/);if(m)return Number(m[1]);m=t.match(/^\s*(\d+)\s*x\b/);if(m)return Number(m[1]);m=t.match(/^\s*x\s*(\d+)\b/);if(m)return Number(m[1]);m=t.match(/\bpack\s+of\s+(\d+)\b/);if(m)return Number(m[1]);m=t.match(/\b(\d+)\s*[x×]\s*\d+(?:\.\d+)?\s*(?:kg|g|ml|l|fl\s*oz|oz)\b/);if(m)return Number(m[1]);m=t.match(/\bmultipack\s+(?:of\s+)?(\d+)\b/);if(m)return Number(m[1]);m=t.match(/\b(?:twin|double)\s*pack\b/);if(m)return 2;m=t.match(/\b(\d+)\s+packs?\b/);if(m)return Number(m[1]);m=t.match(/\b(\d+)\s*pack\b(?=.*\b\d+(?:\.\d+)?\s*(?:kg|g|ml|l|fl\s*oz|oz)\b)/);if(m)return Number(m[1]);return 1}
function sizesCompatible(structured:string,titleSize:string,title:string){if(!structured||!titleSize||sizeEquivalent(structured,titleSize))return true;const a=parseMeasure(structured),b=parseMeasure(titleSize);if(!a||!b||a.u!==b.u)return false;const p=consumerPackQty(title);return p>1&&(Math.abs(a.v*p-b.v)<0.11||Math.abs(b.v*p-a.v)<0.11)}
function inferBrand(title:string,brand:string,known:string[]=[]){const b=clean(brand);if(b&&!DISTRIBUTOR.test(b))return {brand:b,source:'supplied' as const};const cleaned=stripLeadingSalesNoise(title),t=brandKey(cleaned),hit=known.filter(Boolean).sort((a,b)=>b.length-a.length).find(x=>{const k=brandKey(x);return t.startsWith(k+' ')||t===k});if(hit)return {brand:hit,source:'known-title' as const};return {brand:clean(cleaned).replace(/^\([^)]*\)\s*/,'').split(/\s+/)[0]||'',source:'fallback' as const}}
export function isNonProductTitle(title:any){const t=normalize(title);return /\b(compliance labels?|shipping labels?|pallet labels?|packaging service|delivery charge|carriage charge)\b/.test(t)||/^accessories\b/.test(t)||/\b(?:jars?|tubs?)\b/.test(t)&&/\bempty\b/.test(t)||/\bwax paper ice cream tubs?\b/.test(t)||/\bplastic (?:spade )?ice cream spoons?\b/.test(t)||/^1kg bags?$/.test(t)||/^(?:bumerang\b|bright putty\b|fun snaps\b|neon flashing balls\b|spinning top\b|teddy dog toy\b|test_product\b)/.test(t)||/^(?:velo|pablo|killa)\b/.test(t)}
export function parseCanonicalProduct(input:{title:any;brand?:any;size?:any;caseQty?:any},knownBrands:string[]=[],knowledge:ParserKnowledge={}):CanonicalProduct{const aliases=knowledge.brandAliases||[],rawBrand=clean(input.brand),alias=aliases.find((x:any)=>normalize(x.alias)===normalize(rawBrand)),title=cleanProductTitle(input.title);const bi=inferBrand(title,alias?.canonical_brand||rawBrand,[...knownBrands,...aliases.map((x:any)=>x.canonical_brand)]),brand=bi.brand,brandSource=alias?'alias':bi.source;const structuredSize=unitSize(input.size,''),titleSize=unitSize('',title),us=structuredSize||titleSize,qty=Math.max(1,Number(input.caseQty)||1),packQty=consumerPackQty(title);let body=normalize(stripLeadingSalesNoise(title)),nb=normalize(brand);if(nb&&body.startsWith(nb+' '))body=body.slice(nb.length+1);body=body.replace(/\b\d+(?:\.\d+)?\s*(?:kg|g|ml|l|fl\s*oz|oz)\b/g,' ').replace(/\b\d+\s*[x×]\s*\d+(?:\.\d+)?\b/g,' ').replace(/\b(?:case|box|pack)\s*(?:of)?\s*\d+\b/g,' ').replace(/\b\d+\s*(?:pk|pack|ct|count)\b/g,' ').replace(/\b(?:case|box|pack|bags?|cans?|bottles?|tubs?|bars?|multipacks?|pouches?|sharepacks?|sachets?|jars?|trays?)\b/g,' ').replace(/\b(?:usa import|american import|imported|china|canada|aus|australia|bbd|pmp|new|squeeze|slow simmered|slow-simmered|gelatin dessert|jelly mix|instant pudding and pie filling|pie filling)\b/g,' ').replace(/\b\d+ct\b/g,' ');for(const x of knowledge.noiseTerms||[]){const z=normalize(x.term);if(z)body=(' '+body+' ').split(' '+z+' ').join(' ').trim()}body=body.replace(/\bwith\s+(?:whole\s+grain|wholegrains?|natural\s+flavou?rs?|real\s+fruit\s+juice|no\s+artificial\s+(?:colou?rs?|flavou?rs?))\b/g,' ').replace(/\b(?:whole\s+grain|wholegrains?)\b/g,' ').replace(/\s+/g,' ').trim();const generic=new Set(['candy','gummy','soda','drink','energy','flavour','flavor','chewy','peg','theatre','theater','dessert','gelatin','pudding','jelly','squeeze','cereal','whole','grain','with','potato','crisps','crisps','chips','snack','snacks','pieces','piece','original','style','mix']);
const coreCategory=new Set(['cereal','chocolate','sweet','sweets','candy','gum','mints','biscuits','cookies','sauce','syrup','mochi','truffles','crisps','chips','drink','soda']);
const parts=body.split(' ').filter(Boolean),meaningful=parts.filter(x=>!generic.has(x));
const category=parts.find(x=>coreCategory.has(x))||'';
const family=meaningful.slice(0,Math.min(2,meaningful.length)).join(' ')||(category||parts.find(x=>x!=='with')||'');let variant=meaningful.slice(Math.min(2,meaningful.length)).join(' ');const va=(knowledge.variantAliases||[]).filter((x:any)=>!x.brand||normalize(x.brand)===normalize(brand)).filter((x:any)=>phrase(body,x.alias)).sort((a:any,b:any)=>normalize(b.alias).length-normalize(a.alias).length)[0];if(va)variant=va.canonical_variant;const sizeConflict=structuredSize&&titleSize&&!sizesCompatible(structuredSize,titleSize,title)?structuredSize+' vs '+titleSize:'';return {brand,brandSource,family,variant,unitSize:us,caseQty:qty,consumerPackQty:packQty,sizeConflict,canonicalKey:[normalize(brand),normalize(family),normalize(variant),us].filter(Boolean).join('|')}}
const UNDERLYING_DESCRIPTOR=new Set(['chocolate','mini','delights','potato','crisps','crisp','jelly','beans','bean','bag','can','candy','bar','bars','drink','sachet','snack','snacks'])
function underlyingTokens(p:CanonicalProduct){return [...new Set(normalize([p.family,p.variant].filter(Boolean).join(' ')).split(' ').filter(x=>x&&x.length>2&&!UNDERLYING_DESCRIPTOR.has(x)))]}
function subsetIdentity(a:CanonicalProduct,b:CanonicalProduct){const x=underlyingTokens(a),y=underlyingTokens(b);if(!x.length||!y.length)return false;const xs=new Set(x),ys=new Set(y),xInY=x.every(t=>ys.has(t)),yInX=y.every(t=>xs.has(t));return xInY||yInX}
export function canonicalMatch(a:CanonicalProduct,b:CanonicalProduct){if(a.sizeConflict)return {match:false,score:0,reason:'Amazon size conflict: '+a.sizeConflict};if(b.sizeConflict)return {match:false,score:0,reason:'Supplier size conflict: '+b.sizeConflict};const brandOk=brandEquivalent(a.brand,b.brand);if(a.unitSize&&b.unitSize&&!sizeEquivalent(a.unitSize,b.unitSize))return {match:false,score:0,reason:'Unit size conflict'};const fam=normalize(a.family)===normalize(b.family),underlying=subsetIdentity(a,b);if(!brandOk){const fallbackBrand=(a.brandSource==='fallback'||b.brandSource==='fallback')&&fam&&underlying&&!!a.unitSize&&!!b.unitSize&&sizeEquivalent(a.unitSize,b.unitSize);if(!fallbackBrand)return {match:false,score:0,reason:'Brand conflict'};if(a.consumerPackQty>1&&b.caseQty<a.consumerPackQty)return {match:false,score:0,reason:'Supplier case smaller than Amazon sell pack'};return {match:true,score:85,reason:'fallback brand + exact family + underlying unit size'}}if(!fam&&!underlying)return {match:false,score:0,reason:'Family conflict'};const bothHaveVariant=!!a.variant&&!!b.variant,bothSimple=!a.variant&&!b.variant,variantExact=bothHaveVariant&&normalize(a.variant)===normalize(b.variant);if(fam&&bothHaveVariant&&!variantExact&&!underlying)return {match:false,score:0,reason:'Variant conflict'};if(fam&&!bothHaveVariant&&!bothSimple&&!underlying)return {match:false,score:0,reason:'Variant unproven'};if(a.consumerPackQty>1&&b.caseQty<a.consumerPackQty)return {match:false,score:0,reason:'Supplier case smaller than Amazon sell pack'};const size=!a.unitSize||!b.unitSize||sizeEquivalent(a.unitSize,b.unitSize);if(underlying&&(!fam||!variantExact)){const score=size?95:75;return {match:score>=75,score,reason:['underlying unit identity',size?'unit size':'',a.consumerPackQty>1?'sell pack x'+a.consumerPackQty:''].filter(Boolean).join(' + ')}}const score=25+30+25+(size?20:0);return {match:score>=75,score,reason:['family',bothSimple?'simple identity':'variant',size?'unit size':'',a.consumerPackQty>1?'sell pack x'+a.consumerPackQty:''].filter(Boolean).join(' + ')}}
