const DISTRIBUTOR=/distribution|wholesale|wando|spv services|a&a distribution|sweet\s*&?\s*glory|candy\s*cargo/i
export type CanonicalProduct={brand:string;brandSource:'supplied'|'alias'|'known-title'|'fallback';family:string;variant:string;unitSize:string;caseQty:number;consumerPackQty:number;canonicalKey:string;sizeConflict?:string}
export type ParserKnowledge={brandAliases?:any[];variantAliases?:any[];noiseTerms?:any[]}
const clean=(s:any)=>String(s||'').replace(/&amp;|&#x26;/gi,'&').replace(/&#x27;|&#039;|&apos;/gi,"'").replace(/&quot;|&#34;/gi,'"').replace(/\s+/g,' ').trim()
export const normalize=(s:any)=>clean(s).toLowerCase().replace(/\bjell[\s-]*o\b/g,'jello').replace(/strawberries/g,'strawberry').replace(/&/g,' and ').replace(/[^a-z0-9.]+/g,' ').replace(/\s+/g,' ').trim()
const phrase=(hay:string,needle:string)=>(' '+normalize(hay)+' ').includes(' '+normalize(needle)+' ')
export function cleanProductTitle(value:any){let s=clean(value);s=s.replace(/^(?:new\s+)+/i,'').replace(/^\*{1,}\s*/,'').replace(/\*([^*]+)\*/g,'$1').replace(/\s+\*+\s*/g,' ').replace(/^price\s+inc(?:luding)?\s+sugar\s+tax\s+/i,'').replace(/^pack\s+size\s+\d+\s+/i,'').replace(/^model\s+\S+\s+/i,'').replace(/^brand:\s*[^:]+?\s+model:\s*\S+\s+/i,'').replace(/^model:\s*\S+\s+/i,'').replace(/^brand:\s*/i,'').replace(/^.*?popularity\s+alphabetical\s+alphabetical\s+reversed\s+latest\s+popularity\s+0\s+/i,'').replace(/^gen\.?\s+mills\s+/i,'General Mills ');s=s.replace(/\s+([,.;:!?])/g,'$1').replace(/([,.;:!?])(?!\s|$|\d)/g,'$1 ');s=s.split(/\s*[•]\s*|\.\s+(?=[A-Z])/)[0];s=s.replace(/\s+imported\s+from\s+[^.]+.*$/i,'').replace(/\s+wholesale\s+case\s+includes\s+.*$/i,'').replace(/\s+-\s+pack\s+of\s+(\d+)\s*x\s*([\d.]+\s*(?:kg|g|ml|l|fl\s*oz|oz))\b.*$/i,' - $1 x $2').replace(/\s+\((?:usa|china|canada|canadian|aus|australia)\)\s*/ig,' ').replace(/\s+bag\s+bag\b/ig,' Bag');return clean(s)}
const measure=(v:number,u:string)=>u==='kg'?{v:v*1000,u:'g'}:u==='l'?{v:v*1000,u:'ml'}:{v,u}
function measureText(v:number,u:string){const m=measure(v,u);return (Number.isInteger(m.v)?m.v:Number(m.v.toFixed(2)))+m.u}
function allMeasures(v:any){const s=normalize(v),out:{v:number,u:string,text:string}[]=[];const re=/(\d+(?:\.\d+)?)\s*(kg|g|ml|l|fl\s*oz|oz)\b/g;let m;while((m=re.exec(s))){let n=Number(m[1]),u=m[2];if(u==='fl oz'){n*=29.5735;u='ml'}else if(u==='oz'){n*=28.3495;u='g'}const z=measure(n,u);out.push({v:z.v,u:z.u,text:measureText(n,u)})}return out}
export function unitSize(size:any,title:any=''){const structured=allMeasures(size);if(structured.length)return structured[0].text;const ms=allMeasures(title);if(!ms.length)return '';const t=normalize(title);const explicit=t.match(/(?:each|per\s+(?:pack|bag|box|bottle|can))\D{0,12}(\d+(?:\.\d+)?)\s*(kg|g|ml|l|fl\s*oz|oz)\b/);if(explicit){let n=Number(explicit[1]),u=explicit[2];if(u==='fl oz'){n*=29.5735;u='ml'}else if(u==='oz'){n*=28.3495;u='g'}return measureText(n,u)}const x=t.match(/\b\d+\s*[x×]\s*(\d+(?:\.\d+)?)\s*(kg|g|ml|l|fl\s*oz|oz)\b/);if(x){let n=Number(x[1]),u=x[2];if(u==='fl oz'){n*=29.5735;u='ml'}else if(u==='oz'){n*=28.3495;u='g'}return measureText(n,u)}return ms[0].text}
function parseMeasure(s:string){const m=s.match(/^(\d+(?:\.\d+)?)(g|ml)$/);return m?{v:Number(m[1]),u:m[2]}:null}
function sizeEquivalent(a:string,b:string){if(!a||!b)return true;if(a===b)return true;const x=parseMeasure(a),y=parseMeasure(b);if(!x||!y||x.u!==y.u)return false;const tolerance=x.u==='g'?Math.max(1,Math.min(x.v,y.v)*0.015):Math.max(2,Math.min(x.v,y.v)*0.015);return Math.abs(x.v-y.v)<=tolerance}
function brandKey(v:string){return normalize(v).replace(/\b([a-z0-9]+) s\b/g,'$1').trim()}
function brandEquivalent(a:string,b:string){const x=brandKey(a),y=brandKey(b);if(x===y)return true;return x.length>3&&y.length>3&&(x+'s'===y||y+'s'===x)}
// consumerPackQty means separate retail units in the Amazon offer, not pieces inside one retail unit.
// Strong multi-unit evidence: "pack of 3", "3 x 120g", "2 pack ... 120g", "twin pack".
// Bare counts such as "12pk 180g", "8 pieces 120g", "10 count 200g" are treated as internal contents when a single total weight follows.
export function consumerPackQty(title:string){const t=normalize(title);let m=t.match(/\bpack\s+of\s+(\d+)\b/);if(m)return Number(m[1]);m=t.match(/\b(\d+)\s*[x×]\s*\d+(?:\.\d+)?\s*(?:kg|g|ml|l|fl\s*oz|oz)\b/);if(m)return Number(m[1]);m=t.match(/\bmultipack\s+(?:of\s+)?(\d+)\b/);if(m)return Number(m[1]);m=t.match(/\b(?:twin|double)\s*pack\b/);if(m)return 2;m=t.match(/\b(\d+)\s+packs?\b/);if(m)return Number(m[1]);m=t.match(/\b(\d+)\s*pack\b(?=.*\b\d+(?:\.\d+)?\s*(?:kg|g|ml|l|fl\s*oz|oz)\b)/);if(m)return Number(m[1]);return 1}
function sizesCompatible(structured:string,titleSize:string,title:string){if(!structured||!titleSize||structured===titleSize)return true;const a=parseMeasure(structured),b=parseMeasure(titleSize);if(!a||!b||a.u!==b.u)return false;const p=consumerPackQty(title);return p>1&&(Math.abs(a.v*p-b.v)<0.11||Math.abs(b.v*p-a.v)<0.11)}
function inferBrand(title:string,brand:string,known:string[]=[]){const b=clean(brand);if(b&&!DISTRIBUTOR.test(b))return {brand:b,source:'supplied' as const};const t=normalize(title),hit=known.filter(Boolean).sort((a,b)=>b.length-a.length).find(x=>t.startsWith(normalize(x)+' ')||t===normalize(x));if(hit)return {brand:hit,source:'known-title' as const};return {brand:clean(title).replace(/^\([^)]*\)\s*/,'').split(/\s+/)[0]||'',source:'fallback' as const}}
export function isNonProductTitle(title:any){const t=normalize(title);return /\b(compliance labels?|shipping labels?|pallet labels?|packaging service|delivery charge|carriage charge)\b/.test(t)||/^accessories\b/.test(t)||/\b(?:jars?|tubs?)\b/.test(t)&&/\bempty\b/.test(t)||/\bwax paper ice cream tubs?\b/.test(t)||/\bplastic (?:spade )?ice cream spoons?\b/.test(t)||/^1kg bags?$/.test(t)||/^(?:bumerang\b|bright putty\b|fun snaps\b|neon flashing balls\b|spinning top\b|teddy dog toy\b|test_product\b)/.test(t)||/^(?:velo|pablo|killa)\b/.test(t)}
export function parseCanonicalProduct(input:{title:any;brand?:any;size?:any;caseQty?:any},knownBrands:string[]=[],knowledge:ParserKnowledge={}):CanonicalProduct{const aliases=knowledge.brandAliases||[],rawBrand=clean(input.brand),alias=aliases.find((x:any)=>normalize(x.alias)===normalize(rawBrand)),title=cleanProductTitle(input.title);const bi=inferBrand(title,alias?.canonical_brand||rawBrand,[...knownBrands,...aliases.map((x:any)=>x.canonical_brand)]),brand=bi.brand,brandSource=alias?'alias':bi.source;const structuredSize=unitSize(input.size,''),titleSize=unitSize('',title),us=structuredSize||titleSize,qty=Math.max(1,Number(input.caseQty)||1),packQty=consumerPackQty(title);let body=normalize(title),nb=normalize(brand);if(nb&&body.startsWith(nb+' '))body=body.slice(nb.length+1);body=body.replace(/\b\d+(?:\.\d+)?\s*(?:kg|g|ml|l|fl\s*oz|oz)\b/g,' ').replace(/\b\d+\s*[x×]\s*\d+(?:\.\d+)?\b/g,' ').replace(/\b(?:case|box|pack)\s*(?:of)?\s*\d+\b/g,' ').replace(/\b\d+\s*(?:pk|pack|ct|count)\b/g,' ').replace(/\b(?:case|box|pack|bags?|cans?|bottles?|tubs?|bars?|multipacks?|pouches?)\b/g,' ').replace(/\b(?:usa import|china|canada|aus|bbd|pmp|new)\b/g,' ').replace(/\b\d+ct\b/g,' ');for(const x of knowledge.noiseTerms||[]){const z=normalize(x.term);if(z)body=(' '+body+' ').split(' '+z+' ').join(' ').trim()}body=body.replace(/\s+/g,' ').trim();const generic=new Set(['candy','gummy','soda','drink','energy','flavour','flavor','chewy','peg','theatre']);const parts=body.split(' ').filter(Boolean),meaningful=parts.filter(x=>!generic.has(x));const family=meaningful.slice(0,Math.min(2,meaningful.length)).join(' ')||parts.slice(0,2).join(' ');let variant=meaningful.slice(Math.min(2,meaningful.length)).join(' ');const va=(knowledge.variantAliases||[]).filter((x:any)=>!x.brand||normalize(x.brand)===normalize(brand)).filter((x:any)=>phrase(body,x.alias)).sort((a:any,b:any)=>normalize(b.alias).length-normalize(a.alias).length)[0];if(va)variant=va.canonical_variant;const sizeConflict=structuredSize&&titleSize&&!sizesCompatible(structuredSize,titleSize,title)?structuredSize+' vs '+titleSize:'';return {brand,brandSource,family,variant,unitSize:us,caseQty:qty,consumerPackQty:packQty,sizeConflict,canonicalKey:[normalize(brand),normalize(family),normalize(variant),us].filter(Boolean).join('|')}}
export function canonicalMatch(a:CanonicalProduct,b:CanonicalProduct){if(a.sizeConflict)return {match:false,score:0,reason:'Amazon size conflict: '+a.sizeConflict};if(b.sizeConflict)return {match:false,score:0,reason:'Supplier size conflict: '+b.sizeConflict};if(!brandEquivalent(a.brand,b.brand))return {match:false,score:0,reason:'Brand conflict'};if(a.unitSize&&b.unitSize&&!sizeEquivalent(a.unitSize,b.unitSize))return {match:false,score:0,reason:'Unit size conflict'};const fam=normalize(a.family)===normalize(b.family);if(!fam)return {match:false,score:0,reason:'Family conflict'};const bothHaveVariant=!!a.variant&&!!b.variant,bothSimple=!a.variant&&!b.variant;if(bothHaveVariant&&normalize(a.variant)!==normalize(b.variant))return {match:false,score:0,reason:'Variant conflict'};if(!bothHaveVariant&&!bothSimple)return {match:false,score:0,reason:'Variant unproven'};if(a.consumerPackQty>1&&b.caseQty<a.consumerPackQty)return {match:false,score:0,reason:'Supplier case smaller than Amazon sell pack'};const size=!a.unitSize||!b.unitSize||sizeEquivalent(a.unitSize,b.unitSize);const score=25+30+25+(size?20:0);return {match:score>=75,score,reason:['family',bothSimple?'simple identity':'variant',size?'unit size':'',a.consumerPackQty>1?'sell pack x'+a.consumerPackQty:''].filter(Boolean).join(' + ')}}
